apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: PROJECT_NAME_HYPHEN-development
resources:
  - ../base
  - namespace.yaml
  - PROJECT_NAME_HYPHEN-ingress.yaml
images:
  - name: PROJECT_NAME_HYPHEN
    newName: ghcr.io/psdi-uk/PROJECT_NAME_HYPHEN/PROJECT_NAME_HYPHEN
    newTag: 0.0.1
patches:
  - path: deployment-env-patch.yaml
