apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - PROJECT_NAME_HYPHEN-admin-role-binding.yml
  - PROJECT_NAME_HYPHEN-admin-role.yml
  - PROJECT_NAME_HYPHEN-sa-secret.yml
  - PROJECT_NAME_HYPHEN-sa.yml
  - PROJECT_NAME_HYPHEN-deployment.yml
  - PROJECT_NAME_HYPHEN-service.yml
