---
apiVersion: v1
kind: Secret
metadata:
  name: variability-plot-sa-secret
  annotations:
    kubernetes.io/service-account.name: variability-plot-admin-sa
type: kubernetes.io/service-account-token
