apiVersion: apps/v1
kind: Deployment
metadata:
  name: PROJECT_NAME_HYPHEN
spec:
  template:
    spec:
      containers:
        - name: PROJECT_NAME_HYPHEN
          env:
            - name: PRODUCTION_MODE
              value: "true"
