# Workflow for continuous integration tasks run periodically

name: CI - Periodic jobs
run-name: CI - Periodic jobs

on:
  schedule:
    # Run once a week
    - cron: "00 0 1,8,15,22 * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-assets:
    uses: PSDI-UK/psdi-github-workflows-public/.github/workflows/update-common-assets.yml@cb813e85a0616d23527594901b6b856130e5894a
