# Workflow for continuous integration tasks triggered on push to a feature branch

name: CI - Feature branches
run-name: CI - Feature branches
on:
  workflow_dispatch:
  push:
    branches: ["feature**"]

jobs:
  open-pull-request:
    # Open a PR to main if the branch isn't main itself
    if: ${{ github.head_ref || github.ref_name  != 'main' }}
    uses: PSDI-UK/psdi-github-workflows-public/.github/workflows/open-pull-request.yml@b4c884a5fbaa96777c26f1ac6d4eac67531e2fc7
    with:
      target: main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
