# Workflow for continuous integration tasks triggered on pushes to main

name: CI - Main
run-name: CI - Main
on:
  workflow_dispatch:
    inputs:
      skip-tests:
        description: "Don't run tests before deploying"
        required: false
        default: false
        type: boolean
  push:
    branches: ["main"]
    paths:
      - "**/ci-main.yml"
      - "psdi_variability_plot/**"
      - "tests/**"
      - "Dockerfile"
      - "pyproject.toml"

jobs:
  test-all:
    if: ${{ github.event_name == 'push' || ! github.event.inputs.skip-tests }}

    uses: ./.github/workflows/job-test-main.yml
    secrets: inherit # pass all secrets for the environment

  deploy-pages:
    uses: ./.github/workflows/job-publish-pages.yml
    needs: [test-all]
    # Proceed if test-all was successful or skipped
    if: always() &&  (needs.test-all.result == 'skipped' || needs.test-all.result == 'success')

  container-push:
    uses: ./.github/workflows/job-container-push.yml
    needs: [test-all]
    # Proceed if test-all was successful or skipped
    if: always() &&  (needs.test-all.result == 'skipped' || needs.test-all.result == 'success')
    with:
      container_tag: ${{ github.sha }}

  # Deploy to Kubernetes Job
  # Requires an environment, which must reflect the target environment as defined in the
  # GitHub repository: https://github.com/PSDI-UK/psdi-variability-plot/settings/environments
  # The downstream deploy job leverages on Environment specific secrets, which also must be defined
  # For the tag, we need something unique for each push, so we use the SHA of the latest commit
  deploy-stfc-dev-k8s:
    needs: [container-push]
    # Proceed if test-all was successful or skipped
    if: always() && (needs.container-push.result == 'success')
    # Refer to a specific commit for security against supply-chain attacks
    uses: PSDI-UK/psdi-variability-plot-deployment/.github/workflows/job-external-deployment.yaml@c4c4fb99ce149625b94cdc57da39ad45b1281748
    with:
      container_tag: ${{ github.sha }}
      environment: development
    secrets:
      deployment_app_id: ${{ secrets.DEPLOYMENT_APP_ID }}
      deployment_app_private_key: ${{ secrets.DEPLOYMENT_APP_PRIVATE_KEY }}
