# Workflow for continuous integration tasks triggered on pushes to main

name: CI - Main
run-name: CI - Main
on:
  workflow_dispatch:
    inputs:
      skip-tests:
        description: "Don't run tests before deploying"
        required: false
        default: false
        type: boolean
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./psdi_variability_plot
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
      - run: npm install
      - run: npm run build
      - name: Upload JS bundle
        uses: actions/upload-artifact@v7
        with:
          name: js-bundle
          path: psdi_variability_plot/static/js/variability.js

  test-all:
    if: ${{ github.event_name == 'push' || ! github.event.inputs.skip-tests }} && (needs.build.result == 'success')

    uses: ./.github/workflows/job-test-main.yml
    needs: [build]
    secrets: inherit # pass all secrets for the environment

  deploy-pages:
    uses: ./.github/workflows/job-publish-pages.yml
    needs: [test-all]
    # Proceed if test-all was successful or skipped
    if: always() &&  (needs.test-all.result == 'skipped' || needs.test-all.result == 'success')

  container-push:
    uses: ./.github/workflows/job-container-push.yml
    needs: [test-all]
    # When ready to enable this step, remove the following line and uncomment the proper condition below it
    if: false
    # Proceed if test-all was successful or skipped
    # if: always() &&  (needs.test-all.result == 'skipped' || needs.test-all.result == 'success')
    with:
      container_tag: ${{ github.sha }}
  # Deploy to Kubernetes Job
  # Requires an environment, which must reflect the target environment as defined in the
  # GitHub repository: https://github.com/PSDI-UK/psdi-variability-plot/settings/environments
  # The downstream deploy job leverages on Environment specific secrets, which also must be defined
  # For the tag, we need something unique for each push, so we use the SHA of the latest commit
  deploy-stfc-dev-k8s:
    needs: [container-push]
    # Proceed if test-all was successful or skipped
    if: always() && (needs.container-push.result == 'success')
    uses: ./.github/workflows/job-deploy-k8s.yml # use the callable deploy job
    secrets: inherit # pass all secrets for the environment
    with:
      # container_tag
      container_tag: ${{ github.sha }}
      environment: development
