# Workflow for manually triggering deployment of latest release version to the production environment

# It is intended that this workflow be manually triggered after the 'ci-release.yml' job has been shown
# to successfully deploy the latest release version to the staging cluster.

# To be more specific, this workflow deploys the container in the GitHub Container Registry namespace for this
# repo whose tag corresponds to the highest version number, while only considering tags of the form 'v*.*.*',
# where '*' signify non-negative integers.

name: Manual Trigger - Deploy to production cluster
run-name: Deploy to production cluster
on:
  workflow_dispatch:

jobs: # Deploy container with tag to production environment
  deploy-stfc-production-k8s:
    name: Deploy to production
    uses: PSDI-UK/psdi-github-workflows-public/.github/workflows/deploy.yml@b4c884a5fbaa96777c26f1ac6d4eac67531e2fc7
    with:
      deployment_repo: psdi-variability-plot-deployment
      environment: production
      prod: true
      origin: https://organic-toolkit.psdi.ac.uk/variability-plot
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      deployment_app_id: ${{ secrets.DEPLOYMENT_APP_ID }}
      deployment_app_private_key: ${{ secrets.DEPLOYMENT_APP_PRIVATE_KEY }}
